/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_final;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/**
 *
 * @author Boni
 */
public class VentasBidimensional extends javax.swing.JFrame { 
    
    /**
     * Creates new form Ventas
     */
    public VentasBidimensional() {
        initComponents();
        llenarListas();
    }
    private void llenarListas(){
         listaClientes.removeAllItems();
         listaEmpleados.removeAllItems();
         jTable1.setModel(new DefaultTableModel());
        try {
            File f=new File("Empleados.txt");
            FileReader fr= new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea;  
            while((linea = br.readLine())!=null){
                String[] empTemporal=linea.split("%");
                String stringTemporal="";
                for (int i = 0; i < empTemporal.length; i++) {
                stringTemporal+=empTemporal[i]+" ";
                }
                listaEmpleados.addItem(stringTemporal);     
            }
            br.close();
            
        } catch (Exception e) {
        }
        try {
            File f=new File("Clientes.txt");
            FileReader fr= new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea;   
            while((linea = br.readLine())!=null){
                String[] tmp=linea.split("%");
                String tmps="";
                for (String tmp1 : tmp) {
                    tmps += tmp1 + " ";
                }
                listaClientes.addItem(tmps);  
            } 
            br.close();
        } catch (Exception e) {
        }
        jTable1.setModel(new DefaultTableModel());
        try {
            File f=new File("Articulos.txt");
            FileReader fr= new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String linea; 
            MiTabla dm=new MiTabla();
            dm.addColumn("Articulo");
            dm.addColumn("Precio");
            dm.addColumn("Cantidad"); 
            while((linea = br.readLine())!=null){
                String[] artTemporal=linea.split("%"); 
                dm.addRow(new Object[]{artTemporal[0],artTemporal[1],"0"}); 
            }
           
            jTable1.setModel(dm);
            br.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        listaEmpleados = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listaClientes = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jLabel1.setText("Seleccionar empleado");

        jLabel2.setText("Seleccionar cliente");

        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });

        jButton2.setText("Menú Principal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton2KeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton1.setText("Completar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(listaEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(listaClientes, 0, 215, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaClientesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ProyectoTienda p=new ProyectoTienda();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyTyped
          
    }//GEN-LAST:event_jButton2KeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
          try { 
            
            String APC[][]=null;
            String existenciaArticulo[]=null;               //
            File fa=new File("Articulos.txt");  
             if (fa.exists()) { 
                 BufferedReader br=new BufferedReader(new FileReader(fa));
                 String _articulo[];
                 String linea;
                 int ctrlArt=0; 
                 while((linea=br.readLine())!=null){
                     System.out.println(ctrlArt);
                    _articulo=linea.split("%");
                    existenciaArticulo[ctrlArt]=_articulo[2];   
                    ctrlArt++;
                 } 
                 br.close();
             } else {
                 System.out.println("No existe/esta vacio");
             }
            
            
            int j=0;
            for (int i = 0; i < jTable1.getModel().getRowCount(); i++) {//recorre la tabla por completo
                if (jTable1.getModel().getValueAt(i, 2).toString().matches("\\d")) {//El primer if comprueba que el valor sea un digito(Caracter de escape de tipo REGEX) 
                    if (Integer.parseInt(jTable1.getModel().getValueAt(i, 2).toString())>0 && Integer.parseInt(jTable1.getModel().getValueAt(i, 2).toString())<Integer.parseInt(existenciaArticulo[i])) { 
                        for (int k = 0; k < 3; k++) {
                            APC[k][j]=(String)jTable1.getModel().getValueAt(i, k); 
                        }
//                        articulo[j]=(String) jTable1.getModel().getValueAt(i, 0);                     /////CAMBIO DE VARIOS ARREGLOS A ARREGLO BIDIMENSIONAL
//                        precio[j]=Integer.parseInt(jTable1.getModel().getValueAt(i, 1).toString());
//                        cantidad[j]=Integer.parseInt(jTable1.getModel().getValueAt(i, 2).toString());
                        j++;//variable de control (para que no cuente los objetos completos de la tabla sino que contabilice cuantos Tipos de articulo lleva el cliente)
                    }  
                }
            } 
            File fc=new File("Clientes.txt");
             if (fc.exists()) {
                BufferedReader br=new BufferedReader(new FileReader(fc));
                String linea;   
                Cliente c;
                while((linea = br.readLine())!=null){
                    String[] tmp=linea.split("%");
                    if (listaClientes.getSelectedItem().toString().contains(tmp[0])) {
                        c=new Cliente(tmp[0], tmp[1].charAt(0), Persona.estadoCivilInt(tmp[2]),tmp[3] ,Integer.parseInt(tmp[4]), Double.parseDouble(tmp[7]) , new Fecha(tmp[5]));
                    }  
                }
                br.close();
             } else {
                 System.out.println("El archivo de clientes no existe/está vacio");
             }
            
            File fe=new File("Empleados.txt");
             if (fe.exists()) {
                 System.out.println("Empleados existe");
                 BufferedReader br=new BufferedReader(new FileReader(fe));
                 BufferedWriter bw=new BufferedWriter(new FileWriter(fe,true));
                 String linea;
                 String[] _empleados=null;
                 int ctrlLinea=0;  
                 while((linea= br.readLine())!= null){   
                     _empleados[ctrlLinea]=linea;
                     ctrlLinea++;
                 }
                 br.close(); 
                Empleado e; 
                for (int i = 0; i < _empleados.length; i++) { 
                    String[] empTemp = _empleados[i].split("%");
                    System.out.println("entra al for");
                    if (listaEmpleados.getSelectedIndex()==i) { 
                        System.out.println("se encontró el registro preciso"); 
                        e=new Empleado(empTemp[0], empTemp[1].charAt(0), Persona.estadoCivilInt(empTemp[2]) , empTemp[3], new Fecha(empTemp[4])); 
                        e.incrementaVentas(1);
                        if (empTemp.length>4) {
                            bw.write(_empleados[i]);
                            bw.newLine();
                        } else {
                            bw.write(_empleados[i]+"%"+e.getTotalVentas());
                            bw.newLine();
                        } 
                        listaEmpleados.setSelectedIndex(-1);
                    } else {
                        System.out.println("Es otro registro");
                        e=new Empleado();
                        e.incrementaVentas(1);
                       
                        if (empTemp.length>4) {
                            bw.write(_empleados[i]);
                            bw.newLine();
                        } else {
                            bw.write(_empleados[i]+"%"+e.getTotalVentas());
                            bw.newLine();
                        }
                    } 
                }  
                bw.close();
                  
             } else {
                 System.out.println("El archivo de empleados no existe/está vacio");
             }
             System.out.println("Entro al trycatch");
                 
        } catch (Exception e) {
              System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasBidimensional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasBidimensional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasBidimensional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasBidimensional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentasBidimensional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> listaClientes;
    private javax.swing.JComboBox<String> listaEmpleados;
    // End of variables declaration//GEN-END:variables
}
